name: livekit_example
description: Example app that uses LiveKit Flutter SDK
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  flutter_background: ^1.1.0
  permission_handler: ^11.3.1
  provider: ^6.0.1
  logging: ^1.0.1
  shared_preferences: ^2.0.7
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.5
  dropdown_button2: ^2.3.6
  flutter_window_close: ^1.0.0
  collection: '>=1.16.0'

  livekit_client:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/logo-dark.svg
