name: livekit_example
description: Example app that uses LiveKit Flutter SDK
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  flutter_background: ^1.1.0
  provider: ^6.0.1
  logging: ^1.0.1
  shared_preferences: ^2.0.7

  google_fonts: ^2.1.0
  eva_icons_flutter: ^3.0.0
  flutter_svg: ^1.0.0

  livekit_client:
    path: ../
    # git:
    #   url: https://github.com/livekit/client-sdk-flutter
    #   ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/logo-dark.svg
