name: livekit_client
description: Flutter Client SDK for LiveKit
version: 0.4.1
homepage: https://livekit.io

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.6.7
  http: ^0.13.3
  logging: ^1.0.2
  uuid: ^3.0.4
  synchronized: ^3.0.0
  tuple: ^2.0.0
  protobuf: ^2.0.0

  # protobuf:
  #   git:
  #     url: https://github.com/google/protobuf.dart.git
  #     ref: master
  #     path: protobuf/

  # WebSocketChannel has design flaws
  # https://github.com/dart-lang/web_socket_channel/issues/25
  # web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
